// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUxFcxqx0mzIDDYhzZEpyJAbJ_EFeHIzw',
    appId: '1:57660610615:web:da51fb95fbd1af7462c7b2',
    messagingSenderId: '57660610615',
    projectId: 'diary-becbb',
    authDomain: 'diary-becbb.firebaseapp.com',
    storageBucket: 'diary-becbb.firebasestorage.app',
    measurementId: 'G-QW0JG87KTY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXEw7h3OtG2kyd1KcbnYATBtSgtUxlq_I',
    appId: '1:57660610615:android:1e930d5753b71e5562c7b2',
    messagingSenderId: '57660610615',
    projectId: 'diary-becbb',
    storageBucket: 'diary-becbb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd3JJL6NlpDJCO4ncPYZemcytFicGPRx8',
    appId: '1:57660610615:ios:8ffa5c60281cf7ac62c7b2',
    messagingSenderId: '57660610615',
    projectId: 'diary-becbb',
    storageBucket: 'diary-becbb.firebasestorage.app',
    iosBundleId: 'com.example.diaryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd3JJL6NlpDJCO4ncPYZemcytFicGPRx8',
    appId: '1:57660610615:ios:8ffa5c60281cf7ac62c7b2',
    messagingSenderId: '57660610615',
    projectId: 'diary-becbb',
    storageBucket: 'diary-becbb.firebasestorage.app',
    iosBundleId: 'com.example.diaryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUxFcxqx0mzIDDYhzZEpyJAbJ_EFeHIzw',
    appId: '1:57660610615:web:623a45145d9b17fb62c7b2',
    messagingSenderId: '57660610615',
    projectId: 'diary-becbb',
    authDomain: 'diary-becbb.firebaseapp.com',
    storageBucket: 'diary-becbb.firebasestorage.app',
    measurementId: 'G-C0H9S8VX09',
  );
}

